/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/BackToTop/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    DragSelect: typeof import('./src/components/DragSelect/index.vue')['default']
    DropdownMenu: typeof import('./src/components/Share/DropdownMenu.vue')['default']
    Dropzone: typeof import('./src/components/Dropzone/index.vue')['default']
    EditorImage: typeof import('./src/components/Tinymce/components/EditorImage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ErrorLog: typeof import('./src/components/ErrorLog/index.vue')['default']
    GithubCorner: typeof import('./src/components/GithubCorner/index.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./src/components/HeaderSearch/index.vue')['default']
    ImageCropper: typeof import('./src/components/ImageCropper/index.vue')['default']
    Keyboard: typeof import('./src/components/Charts/Keyboard.vue')['default']
    LineMarker: typeof import('./src/components/Charts/LineMarker.vue')['default']
    Mallki: typeof import('./src/components/TextHoverEffect/Mallki.vue')['default']
    MDinput: typeof import('./src/components/MDinput/index.vue')['default']
    MixChart: typeof import('./src/components/Charts/MixChart.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    PanThumb: typeof import('./src/components/PanThumb/index.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/index.vue')['default']
    SingleImage: typeof import('./src/components/Upload/SingleImage.vue')['default']
    SingleImage2: typeof import('./src/components/Upload/SingleImage2.vue')['default']
    SingleImage3: typeof import('./src/components/Upload/SingleImage3.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect/index.vue')['default']
    Sticky: typeof import('./src/components/Sticky/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Tinymce: typeof import('./src/components/Tinymce/index.vue')['default']
    UploadExcel: typeof import('./src/components/UploadExcel/index.vue')['default']
    VueCountTo: typeof import('./src/components/vue-count-to/vue-countTo.vue')['default']
  }
}
